### ISSUE TITLE
Should use slug as function prefix instead of default wds_acme

### ISSUE THREAD

**Issue by donmhico** [WebDevStudios/wd_s-generator#18]
The form generator is only requiring "Name" which will be converted as the "theme slug". For example, if I used "Mico" as the Theme Name, I would expect that both "Text Domain" and "Function Prefix" would be "mico".

The text domain is indeed set to "mico".

![1](https://user-images.githubusercontent.com/5747475/119843427-1ff39e80-bf3a-11eb-812c-37cdc4ae5b0d.jpg)

However, the function prefix used is "wds_acme" instead of "mico".

![2](https://user-images.githubusercontent.com/5747475/119843576-43b6e480-bf3a-11eb-8608-265f56b21694.jpg)

**Comment by daveromsey** [comment]
Closing this because wd_s now uses PHP namespaces instead of a function prefix, and the issue highlighted in the ticket is no-longer present.
