### ISSUE TITLE
Automatic submodule update & deployment

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s-generator#4]
Use Github's webhooks to trigger this command each time we push to master on wd_s

``` bash
git submodule foreach git checkout master && git submodule foreach --recursive git pull origin master
```

Then I won't have to maintain that submodule...

**Comment by bradp** [comment]
I'd love to work on this!

**Comment by gregrickaby** [comment]
I've setup the [WDS Build Scripts](https://github.com/WebDevStudios/WDS-Build-Scripts) to handle automatic deployments + builds anytime we push to master both in this repo, and the [wd_s](https://github.com/WebDevStudios/wd_s)
